### ISSUE TITLE
Text area width

### ISSUE THREAD

**Issue by dgleba** [carmaz79/xataface-responsive-theme#3]
The text area's are quite narrow.
Can you suggest how to make them wider?

![2017-02-03 21_21_13-new record - opera](https://cloud.githubusercontent.com/assets/4622715/22614879/e7670ef6-ea56-11e6-8f50-dffdb9bf01a7.png)

**Comment by carmaz79** [comment]
This does not happen to me.
I updated all theme another time. 
Maybe some file would not have been updated.
Download and try. 

Clear cache and templates_c directory first of all, after update.
Play with these directives on fields.ini file on the target field of course:
http://xataface.com/wiki/widget%3Aatts
display = inline

Do you use templates in your application?

I updated all theme another time. 
Maybe some file would not have been updated.
Download and try.

**Comment by dgleba** [comment]
I downloaded latest git repo again, cleared cache and templates_c directory, and things are better.

To clear the font awesome js error, I symlinked the egrappler module into the app modules folder.

I put egrappler in an entirley seperate new folder and symlinked it.

```#ln -s real-life-folder thing2point2it-withoutlastfolder  
#ln -s /va/ww/1 /h   # creates /h/1  
fakedir1='/var/www/html/shiftcsd1r/modules'  
mkdir -p $fakedir1  
ln -s /var/www/html/xataface-modules-link/egrappler $fakedir1  
```

This is what I have now..

![2017-02-04 12_41_59-text area width issue 3 carmaz79_xataface-responsive-theme](https://cloud.githubusercontent.com/assets/4622715/22620325/66b5a138-ead7-11e6-9e94-4c2a4ab3dae7.png)

Text area's are now better..

![2017-02-04 12_43_42-bruce brodhagen - egrappler csd1 shift reports - opera](https://cloud.githubusercontent.com/assets/4622715/22620335/ae0d1002-ead7-11e6-9559-08f1d6e8e5eb.png)
